name: coverage-upload
description: upload coverage reports to Backstage
author: Søren Mathiasen
inputs:
  server: 
    description: Server URL
    default: https://backstage.ts.sv
    required: false
  file:
    description: file path to the coverage file
    required: true
  name:
    description: name of the component in Backstage
    required: true
  type:
    description: the type of the coverage report - cobertura or jacoco
    default: cobertura
    required: false
  ca-cert:
    description: MTLS ca cert
    required: false
  client-cert:
    description: MTLS client cert
    required: false
  client-key:
    description: MTLS client key
    required: false
runs:
  using: node12
  main: dist/index.js
